apiVersion: apps/v1
kind: Deployment
metadata:
  name: myks-test
spec:
  selector:
    matchLabels:
      app: myks-test
  template:
    metadata:
      labels:
        app: myks-test
    spec:
      containers:
      - name: myks-test
        image: apmtestregistry.southcentralus.data.azurecr.io:myfirst
        ports:
          - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: acr-secret