apiVersion: v1
kind: Service
metadata:
    name: "aksapmcluster-5ed4"
    labels:
        app: "aksapmcluster-5ed4"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "aksapmcluster-5ed4"