apiVersion: v1
kind: Service
metadata:
    name: "apmaks-7f90"
    labels:
        app: "apmaks-7f90"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "apmaks-7f90"